spring:
    application:
        name: course-administrator-service
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/${name.postgresql.db}
        username: ${user.postgresql}
        password: ${password.postgresql}
    data:
      mongodb:
          uri: ${mongo.db}
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update
security:
    jwt:
        secret: ${secret.jwt}